[[skills.config]]
path = "/Users/tapppe/.agents/skills/brainstorming/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/tapppe/.agents/skills/requesting-code-review/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/tapppe/.agents/skills/skill-creator/SKILL.md"
enabled = false
